### ISSUE TITLE
Get-AdoTeamMember doesn't work

### ISSUE THREAD

**Issue by the-paras** [Azure-Devops-PowerShell-Module/AzDevOps#56]
The Get-AdoTeamMember cmdlet is not returning any member list even if you pass project id, team id details correctly.

**Comment by szymonbr** [comment]
Indeed, it doesn't work. 

When `project` or `projectid` param is provided only then the following error is returned
```
Get-AdoTeam : Cannot process argument transformation on parameter 'TeamId'. Cannot convert null to type "System.Guid".
At ...\WindowsPowerShell\Modules\azdevops\2.1.0\core\core.psm1:422 char:56
+ ...    $Team = Get-AdoTeam -ProjectId $Project.Id -TeamId $TeamId -Verbos ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AdoTeam], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-AdoTeam
```

When `project` and `teamid` params are provided then the following error is returned
```
Invoke-RestMethod :
Bad Request
Bad Request - Invalid URL
HTTP Error 400. The request URL is invalid.
At ...\WindowsPowerShell\Modules\azdevops\2.1.0\AzDevOps.psm1:96 char:14
+ ...     return (Invoke-RestMethod -Uri $Uri.AbsoluteUri -Method $Method - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

When `projectid` and `teamid` params are provided then the cmdlet just returns nothing.

**Comment by jeffpatton1971** [comment]
This is a case of me trying to be too detailed oriented, at some point the URL is getting corrupted, this work will get rolled in to #39 and I'll see about getting that all finished this weekend. I've been swamped with work.

**Comment by jeffpatton1971** [comment]
Actually I'm going to refactor all of this, so I'll create a new issue that I think encapsulates what the real problem is and see if ic an't just knock that out today

**Comment by jeffpatton1971** [comment]
This should be working now, you will need to grab the latest version 3.0.0
